memory_limit = 4G
post_max_size = 20M
upload_max_filesize = 20M

# Xdebug 2
#xdebug.remote_enable=1
#xdebug.remote_autostart=1
#xdebug.remote_connect_back=1
#xdebug.remote_host=host.docker.internal
#xdebug.remote_port=9000

# Xdebug 3
#xdebug.mode=debug
#xdebug.start_with_request=yes
#xdebug.client_host=host.docker.internal
#xdebug.client_port=9003
#xdebug.idekey=VSCODE

; 2026-08-03: disable xdebug in web SAPI (was loading in 'develop' mode,
; adding per-request overhead). Re-enable for debugging by uncommenting
; xdebug.mode=debug below (and remove the =off line).
xdebug.mode=off
